/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-10-28 15:41:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"BootstrapMetro/docs/css/metro-bootstrap.css\">\r\n");
      out.write("        <script src=\"BootstrapMetro/docs/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"BootstrapMetro/docs/js/jquery/jquery.widget.min.js\"></script>\r\n");
      out.write("        <script src=\"BootstrapMetro/min/metro.min.js\"></script>\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"images/remote_control.ico\" />\r\n");
      out.write("\t    <title>SuperRemotely</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"metro\">\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<nav class=\"navigation-bar dark fixed-top\">\r\n");
      out.write("\t<nav class=\"navigation-bar-content\">\r\n");
      out.write("        <ul class=\"element-menu\">\r\n");
      out.write("        \t<li><a href=\"/RPi\">Home</a></li>\r\n");
      out.write("        \t<li><a href=\"./Devices\">Devices</a></li>\r\n");
      out.write("        \t<li><a href=\"./Action\">Actions</a></li>\r\n");
      out.write("        \t<li><a href=\"./Sequence\">Sequences</a></li>\r\n");
      out.write("        \t<li><a href=\"#Alarm\">Alarm</a></li>\r\n");
      out.write("        \t<li>\r\n");
      out.write("                <a class=\"dropdown-toggle\" href=\"#Options\">Options</a>\r\n");
      out.write("                <ul class=\"dropdown-menu dark\" data-role=\"dropdown\" style=\"display: none;\">\r\n");
      out.write("                \t<li><a href=\"#Time\">Set the time</a></li>\r\n");
      out.write("                    <li><a href=\"#Record\">Record new action</a></li>\r\n");
      out.write("                    <li><a href=\"#Add\">Add a new Device</a></li>\r\n");
      out.write("                    <li><a href=\"#Remove\">Remove a device</a></li>\r\n");
      out.write("                    <li><a href=\"#Edit\">Remove an action</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("    </nav>\t\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Body -->\r\n");
      out.write("<div class=\"grid\" style=\"margin-left:20px;margin-top:60px\">\r\n");
      out.write("\t\r\n");
      out.write("\t<form method=\"post\" action=\"Blink\">\r\n");
      out.write("\t\t<input name=\"button\" class=\"bg-green bg-hover-lime fg-white\" type=\"submit\" value=\"LET THERE BE LIGHT1\" style=\"font-size:40px; height:200px; width:600px;\">\r\n");
      out.write("\t\t<input name=\"button\" class=\"bg-green bg-hover-lime fg-white\" type=\"submit\" value=\"LET THERE BE LIGHT2\" style=\"font-size:40px; height:200px; width:600px;\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
